<?php
define('YOUR_DEFINED_CONST', 'Your defined constant value!');

return [
//SandBox
	//'PAYPAL_CLIENT_ID'         => 'AU8I5JaKCPH_oPlrTV9sOXr6BrmKOITwEYnQpEN_--DlBcRuSiQF2AupJ86Kzp8teI6lQT2GRI38b0sR',
	//'PAYPAL_CLIENT_SECRET'     => 'ECndEVaLe52anMhESAXef7o2sNk9E9jFYSvx46V9L69WZydQjEVXKcxU9LP27tPgxlzMeGba_iwTBv2T',	
//Live
	'PAYPAL_CLIENT_ID'         => 'AcfOVolzUaAmJ5KmW7TnbCUDiboC4WPTvW9yIG5qCIjgyvNbPH_eO4tWpm-zYjp9V0G6TOK81tegdK1R',
	'PAYPAL_CLIENT_SECRET'     => 'ENo6kTUm8nWU5dN7AgZpW5k1plZZnoBHLxEuM4dRuBN-zypPgbllvrSmoGdDW8vCkh9Z9BhLAD5QDuAf',
	
	'AUTHORIZATION_SERVER_KEY' => 'AAAA_BttwaQ:APA91bHHFCxSdPw-nr5_JTCCkHwGLq3cNX4Ys32E66b3ljOCC4bzhRDVpQvUtsbrFwmNRWph9QtKYGFSufcOHGh2ZhGCAFH8Z6p1UMs4wFnUdRurUHzWWiFQG5Kfp_0umIpB9McI8IaA'
]; 